name: Merge Music

on:
  workflow_dispatch:
  push:
    paths:
      - "music/*.mp3"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Re-encode all MP3s to valid format
        run: |
          mkdir fixed
          for f in music/*.mp3; do
            if [ -s "$f" ]; then
              echo "Re-encoding $f ..."
              ffmpeg -y -i "$f" -vn -acodec libmp3lame -ar 44100 -ab 192k "fixed/$(basename "$f")" || true
            else
              echo "Skipping empty file $f"
            fi
          done
          rm -rf music
          mv fixed music

      - name: Merge all MP3 files with crossfade
        run: |
          files=(music/*.mp3)
          n=${#files[@]}

          if [ $n -eq 0 ]; then
            echo "No MP3 files found!"
            exit 1
          elif [ $n -eq 1 ]; then
            echo "Only one file, copying directly..."
            ffmpeg -y -i "${files[0]}" -c:a libmp3lame merged.mp3
          else
            inputs=""
            filter=""

            for f in "${files[@]}"; do
              inputs="$inputs -vn -i \"$f\""
            done

            for i in $(seq 0 $((n-2))); do
              if [ $i -eq 0 ]; then
                filter="[0:a][1:a]acrossfade=d=5:c1=tri:c2=tri[a1]"
              else
                filter="$filter;[a$i][$(($i+1)):a]acrossfade=d=5:c1=tri:c2=tri[a$(($i+1))]"
              fi
            done

            last="[a$((n-1))]"

            eval ffmpeg $inputs -filter_complex "$filter" -map "$last" -c:a libmp3lame merged.mp3
          fi

      - name: Upload merged music
        uses: actions/upload-artifact@v4
        with:
          name: merged-music
          path: merged.mp3
          retention-days: 1
